# Generated by Django 3.1.5 on 2021-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210214_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='who',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='whom',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
