# Generated by Django 3.1.5 on 2021-03-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210307_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
