# Generated by Django 3.1.5 on 2021-03-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
