# Generated by Django 3.1.5 on 2021-02-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userposts',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
