# Generated by Django 3.1.5 on 2021-02-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='password',
            field=models.CharField(max_length=500, verbose_name='password'),
        ),
    ]
