# Generated by Django 3.1.5 on 2021-02-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210214_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='subscription',
        ),
        migrations.AddField(
            model_name='newuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
